version: '3.6'

services:
  demo-a:
    image: petewoods/demoa
    environment:
      SPRING_ZIPKIN_BASEURL: 'http://zipkin:9411'
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: '1.0'
      SPRING_SLEUTH_SAMPLER_PROBABILITY: '1.0'
      SPRING_ZIPKIN_SERVICE_NAME: 'demoA'
    ports:
      - 8080:8080

  demo-b:
    image: petewoods/demob
    environment:
      SPRING_ZIPKIN_BASEURL: 'http://zipkin:9411'
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: '1.0'
      SPRING_SLEUTH_SAMPLER_PROBABILITY: '1.0'
      SPRING_ZIPKIN_SERVICE_NAME: 'demoB'

  demo-c:
    image: petewoods/democ
    environment:
      SPRING_ZIPKIN_BASEURL: 'http://zipkin:9411'
      SPRING_SLEUTH_SAMPLER_PERCENTAGE: '1.0'
      SPRING_SLEUTH_SAMPLER_PROBABILITY: '1.0'
      SPRING_ZIPKIN_SERVICE_NAME: 'demoC'

  zipkin:
    image: 'openzipkin/zipkin'
    ports:
      - 9411:9411